name: untitled
version: '1.0-SNAPSHOT'
main: org.hustlehard.sethome.SetHomePlugin
api-version: '1.21'

commands:
  sethome:
    description: 'Задает точку дома'
    usage: '/sethome <homeName>'
  home:
    description: 'Телепортирует в указанную точку если она существует'
    usage: '/home <homeName>'
  homes:
    description: 'Показывает все дома игрока.'
    usage: '/homes'